apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ykxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ykxx
    app.kubernetes.io/part-of: test-app-bjtj
  name: test-component-ykxx
  namespace: build-e2e-hacbs-qlpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-ykxx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-ykxx
    spec:
      containers:
      - image: quay.io/xinjiang/test-images:9a7c2f60672044959395db8c2a76d103
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
